name: Model Retraining

on:
  schedule: # At midnight on the 1st and 15th of each month
    - cron: '0 0 1,15 * *'  

jobs:
  retraining:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Retrain Model
        run: python src/retrain.py
